Suvienytos consumer ir employee klases tarp saves ir buvusiu laikinu auth klasiu.
Susikompiliuoja, taciau:

System.InvalidOperationException: The entity type 'EmployeeServiceQualification' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.